global using Microsoft.AspNetCore.Http;
global using System.ComponentModel.DataAnnotations;
global using Baraka_Savdo.DataAccess.Utils;
global using Baraka_Savdo.Service.Interfaces.Common;
global using Newtonsoft.Json;
global using Baraka_Savdo.Domain.Entities.Categories;
global using Baraka_Savdo.Service.Dtos.Categories;
global using Baraka_Savdo.DataAccess.ViewModels.Users;
global using Baraka_Savdo.Service.Dtos.Users;